# Generated by Django 5.1.7 on 2025-03-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_activity_description_alter_activity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitybooking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='activitybooking',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
