# Generated by Django 5.1.7 on 2025-03-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_activitybooking_email_activitybooking_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitybooking',
            name='total_price',
        ),
        migrations.AddField(
            model_name='activitybooking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
