# Generated by Django 5.1.7 on 2025-03-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_activitybooking_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='recommended_destinations',
            field=models.ManyToManyField(blank=True, to='app1.destination'),
        ),
    ]
