# Generated by Django 5.1.7 on 2025-03-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_destination_recommended_destinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('beach', 'Beach'), ('mountain', 'Mountain'), ('historical', 'Historical'), ('city', 'City'), ('adventure', 'Adventure'), ('nature', 'Nature')], max_length=100),
        ),
    ]
