# Generated by Django 5.1.7 on 2025-03-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_activitybooking_profile_activitybooking_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitybooking',
            name='user',
        ),
    ]
