# Generated by Django 5.1.7 on 2025-03-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_activitybooking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitybooking',
            old_name='price',
            new_name='total_price',
        ),
    ]
